### ISSUE TITLE
Repetitive text in Chapter 3

### ISSUE THREAD

**Issue by monica-chang** [davidkane9/PPBDS#283]
there's some repetitive text at around "...Instead of considering the treatment in terms of duration, we could also consider different volume levels at which Spanish is being spoken..."

**Comment by davidkane9** [comment]
Fixed. Thanks!

**Comment by sophie-z-li** [comment]
Two repeating sentences in Chapter 4 functions chapter: "If you run the function name without its parentheses, R will return the code that makes up the function." 

Would recommend deleting the first sentence because the following example demonstrates what happen when one inputs a function *with parenthesis*

**Comment by sophie-z-li** [comment]
Another sentence duplicate in the Anonymous Functions section:

_Let’s “eyeball” the first few results using str()._

I think the first duplicate one should probably be removed for content harmony.

**Comment by sophie-z-li** [comment]
Chapter 4, Section 4.4.3

_What we’ve accomplished:

-We’ve generalized our dice throwing function to take in a custom value for n
-We’ve specified a default value: n=2_

I think for the second bullet point, we actually specified the default value to be n = 1 in the referred-to example.
